solon.app:
  name: 'demo-app'
  group: 'demo'

server:
  port: 8081
  contextPath: /api #可选

cas:
  #CAS服务端地址
  cas-server-url-prefix: https://localhost:8443/cas
  #CAS服务端登录地址
  cas-server-login-Url: ${cas.cas-server-url-prefix}/login
  #应用系统地址
  server-name: http://localhost:8081
  #受保护的url前缀
  authentication-url-patterns: /admin/*
  #认证成功重定向地址
  redirect-url-success: ${cas.server-name}/#/Index
  #注销登录重定向地址，service=http://localhost:8034/api/admin/auth 是API服务认证接口的地址
  redirect-url-logout: ${cas.cas-server-url-prefix}/logout?service=http%3A%2F%2Flocalhost%3A8034%2Fapi%2Fadmin%2Fauth
